-- ═══════════════════════════════════════════════════════════════
-- DONNEES GENEALOGIQUES - Famille Aly Koira
-- Genere automatiquement depuis data/members.js
-- 342 membres | 2026-01-31
-- ═══════════════════════════════════════════════════════════════

-- Vider la table avant insertion (optionnel)
-- TRUNCATE TABLE members;

-- ══════════════════════════════════════════════════════════
-- GENERATION 0 (1 membres)
-- ══════════════════════════════════════════════════════════

INSERT INTO members (id, name, alias, gender, generation, father_id, mother_ref, spouses, children) VALUES
  ('hamatou_lassane', 'Hamatou Lassane', 'Koro', 'M', 0, NULL, NULL, '{}', '{"lalla_hamatou","mahamane_h"}')
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  alias = EXCLUDED.alias,
  gender = EXCLUDED.gender,
  generation = EXCLUDED.generation,
  father_id = EXCLUDED.father_id,
  mother_ref = EXCLUDED.mother_ref,
  spouses = EXCLUDED.spouses,
  children = EXCLUDED.children;

-- ══════════════════════════════════════════════════════════
-- GENERATION 1 (3 membres)
-- ══════════════════════════════════════════════════════════

INSERT INTO members (id, name, alias, gender, generation, father_id, mother_ref, spouses, children) VALUES
  ('alkamahamane', 'Alkamahamane Sabalkaidi', NULL, 'M', 1, NULL, NULL, '{"lalla_hamatou"}', '{"goussoumbi","goma","hounaye","soumboulou","farimata_alk","ali"}'),
  ('lalla_hamatou', 'Lalla Hamatou Lassane Koro', NULL, 'F', 1, 'hamatou_lassane', '(à définir)', '{"alkamahamane"}', '{"goussoumbi","goma","hounaye","soumboulou","farimata_alk","ali"}'),
  ('mahamane_h', 'Mahamane Hamatou Lashane Almansour', 'Koro Souafou Jaouder boun Zarkoum', 'M', 1, 'hamatou_lassane', '(à définir)', '{"Farimata Aliou Gourmanthia"}', '{"alkaido","alamiro","assoura","aliou_mh","abouchamataye","aicha_mh","gombo","adiza_mh","aboubaye_mh"}')
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  alias = EXCLUDED.alias,
  gender = EXCLUDED.gender,
  generation = EXCLUDED.generation,
  father_id = EXCLUDED.father_id,
  mother_ref = EXCLUDED.mother_ref,
  spouses = EXCLUDED.spouses,
  children = EXCLUDED.children;

-- ══════════════════════════════════════════════════════════
-- GENERATION 2 (15 membres)
-- ══════════════════════════════════════════════════════════

INSERT INTO members (id, name, alias, gender, generation, father_id, mother_ref, spouses, children) VALUES
  ('goussoumbi', 'Goussoumbi Alkamahamane', NULL, 'M', 2, 'alkamahamane', 'lalla_hamatou', '{"Aissa Mahamane Hamatou"}', '{"alphary_g","garba_g","klimazou"}'),
  ('goma', 'Goma Alkamahamane', NULL, 'M', 2, 'alkamahamane', 'lalla_hamatou', '{}', '{"sidiki_g"}'),
  ('hounaye', 'Hounaye (Hounna) Alkamahamane', NULL, 'M', 2, 'alkamahamane', 'lalla_hamatou', '{"Ibannia Albichir"}', '{"hallachi_h","aissa_h","tayda_h"}'),
  ('soumboulou', 'Soumboulou Alkamahamane', NULL, 'F', 2, 'alkamahamane', 'lalla_hamatou', '{"Alphaga Labassou Saye"}', '{"kohondo","sagayo","tassaye"}'),
  ('farimata_alk', 'Farimata Alkamahamane', NULL, 'F', 2, 'alkamahamane', 'lalla_hamatou', '{}', '{"dalla"}'),
  ('ali', 'Ali Alkamahamane', 'Aly Koïra', 'M', 2, 'alkamahamane', 'lalla_hamatou', '{"Waykounga Samba","Farimata Alassane","Fouga Alassane Hamatou"}', '{"mahamane","babachigaw","kobbo","moussa","omorou","tamimoune","mahadi"}'),
  ('alkaido', 'Alkaido Mahamane', NULL, 'M', 2, 'mahamane_h', 'Farimata Aliou Gourmanthia', '{"Hawa Alkaidi Bokar"}', '{"halimatou_alk","mohomodou_alk","fadimata_alk","bana","hailalle","zahara_alk"}'),
  ('alamiro', 'Alamiro Mahamane', NULL, 'M', 2, 'mahamane_h', 'Farimata Aliou Gourmanthia', '{}', '{}'),
  ('assoura', 'Assoura Mahamane', NULL, 'M', 2, 'mahamane_h', 'Farimata Aliou Gourmanthia', '{}', '{}'),
  ('aliou_mh', 'Aliou Mahamane', NULL, 'M', 2, 'mahamane_h', '(à définir)', '{}', '{}'),
  ('abouchamataye', 'Abouchamataye Mahamane', NULL, 'M', 2, 'mahamane_h', '(à définir)', '{}', '{}'),
  ('aicha_mh', 'Aïcha Mahamane', NULL, 'F', 2, 'mahamane_h', '(à définir)', '{}', '{}'),
  ('gombo', 'Gombo Mahamane', NULL, 'M', 2, 'mahamane_h', 'Farimata Aliou Gourmanthia', '{}', '{}'),
  ('adiza_mh', 'Adiza Mahamane', NULL, 'F', 2, 'mahamane_h', '(à définir)', '{}', '{}'),
  ('aboubaye_mh', 'Aboubaye Mahamane', NULL, 'M', 2, 'mahamane_h', '(à définir)', '{}', '{}')
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  alias = EXCLUDED.alias,
  gender = EXCLUDED.gender,
  generation = EXCLUDED.generation,
  father_id = EXCLUDED.father_id,
  mother_ref = EXCLUDED.mother_ref,
  spouses = EXCLUDED.spouses,
  children = EXCLUDED.children;

-- ══════════════════════════════════════════════════════════
-- GENERATION 3 (24 membres)
-- ══════════════════════════════════════════════════════════

INSERT INTO members (id, name, alias, gender, generation, father_id, mother_ref, spouses, children) VALUES
  ('alphary_g', 'Alphary Goussoumbi', NULL, 'M', 3, 'goussoumbi', 'Aissa Mahamane Hamatou', '{"Tamimoune Ali"}', '{"chiddaye","mata_a","ichata_a","boudjal","saleymatou"}'),
  ('garba_g', 'Garba Goussoumbi', NULL, 'F', 3, 'goussoumbi', 'Aissa Mahamane Hamatou', '{"Alhady"}', '{"hamadahamane_al","albakaya_al","yahiya_al","ndolly_al","hajarata_al"}'),
  ('klimazou', 'Klimazou Goussoumbi', NULL, 'M', 3, 'goussoumbi', 'Aissa Mahamane Hamatou', '{}', '{"mahamadou_k"}'),
  ('sidiki_g', 'Sidiki Goma', NULL, 'M', 3, 'goma', NULL, '{}', '{}'),
  ('hallachi_h', 'Hallachi Hounna', NULL, 'M', 3, 'hounaye', 'Ibannia Albichir', '{}', '{}'),
  ('aissa_h', 'Aissa Hounna', NULL, 'F', 3, 'hounaye', 'Ibannia Albichir', '{}', '{}'),
  ('tayda_h', 'Tayda Hounna', NULL, 'M', 3, 'hounaye', 'Ibannia Albichir', '{}', '{}'),
  ('kohondo', 'Kohondo Alphaga Labassou Saye', NULL, 'F', 3, NULL, 'soumboulou', '{}', '{}'),
  ('sagayo', 'Sagayo Alphaga Labassou Saye', NULL, 'M', 3, NULL, 'soumboulou', '{}', '{}'),
  ('tassaye', 'Tassaye Alphaga Labassou Saye', NULL, 'F', 3, NULL, 'soumboulou', '{}', '{}'),
  ('mahamane', 'Mahamane Ali', NULL, 'M', 3, 'ali', 'Waykounga Samba', '{"Aïcha Houneye","Adijatou Hamma (Hadizatou)","Aïcha Hamma"}', '{"mohomone","taya","ahmadou","yata","issouf","halilou","alhalil","aliou_m","houzaye","alassane_s","agaicha_m","abdou_d"}'),
  ('babachigaw', 'Babachigaw Ali', NULL, 'M', 3, 'ali', 'Farimata Alassane', '{"Halimatou Mohomodou"}', '{"aliou_b","aboubacar","ousmane_a","alhousseini","abdoulaye_s","nouhoum","mata_b"}'),
  ('kobbo', 'Agacha Ali', 'Kobbo', 'F', 3, 'ali', 'Fouga Alassane', '{"Fedja Zongo","Mouhammadou Gagay","Taïda Houneï"}', '{"aicha_f","arhamatou_f","issa_m","taya_m","izeboncana","jaouja","dally"}'),
  ('moussa', 'Moussa Ali', NULL, 'M', 3, 'ali', 'Fouga Alassane', '{"Habïlatou Mama"}', '{"mata_m","haylloli","wanaissou_m","jato","alassane_m","assoumane_m","abdou_m","sala"}'),
  ('omorou', 'Omorou Ali', NULL, 'M', 3, 'ali', 'Fouga Alassane', '{"Cheffou Aliou"}', '{"houssouba","kabongou","mahamadou_o","sourgou","tabbo_o","zabbo","ichata_o"}'),
  ('tamimoune', 'Tamimoune Ali', NULL, 'F', 3, 'ali', 'Fouga Alassane', '{"Alphary Goussoumbi"}', '{"chiddaye","mata_a","ichata_a","boudjal","saleymatou"}'),
  ('mahadi', 'Mahadi Ali', NULL, 'M', 3, 'ali', 'Fouga Alassane', '{"Aldjannatou Ahmadou"}', '{"dayo","saffia","sawde","zarha","aminta_m","chaffa","seydou_m"}'),
  ('dalla', 'Dalla', NULL, 'M', 3, NULL, 'farimata_alk', '{}', '{}'),
  ('halimatou_alk', 'Halimatou Alkaido', 'Goungou', 'F', 3, 'alkaido', 'Hawa Alkaidi Bokar', '{"Aboubaye Kouwal dit Idrissa"}', '{"omorou_ab","hamaya","farimata_ab"}'),
  ('mohomodou_alk', 'Mohomodou Alkaido', NULL, 'M', 3, 'alkaido', 'Hawa Alkaidi Bokar', '{"Fatoumata Molla Kader"}', '{"halimatou_moh","alkalifa","ichata_moh","tabati","djinna","abacar_moh"}'),
  ('fadimata_alk', 'Fadimata Alkaido', NULL, 'F', 3, 'alkaido', 'Hawa Alkaidi Bokar', '{"Moyadji Alkaidi Mohouta Bacha"}', '{"kabongou_moy","boubaye_moy","alhassane_moy","agacha_moy"}'),
  ('bana', 'Bana Alkaido', NULL, 'F', 3, 'alkaido', 'Hawa Alkaidi Bokar', '{}', '{"oura"}'),
  ('hailalle', 'Hailalle Alkaido', NULL, 'F', 3, 'alkaido', 'Hawa Alkaidi Bokar', '{"Chirime Hamane de Bamba"}', '{"abdoulaye_ch","abacar_ch","mouazou","fatto","ibrayhawi"}'),
  ('zahara_alk', 'Zahara Alkaido', NULL, 'F', 3, 'alkaido', 'Hawa Alkaidi Bokar', '{}', '{"abacar_sidi"}')
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  alias = EXCLUDED.alias,
  gender = EXCLUDED.gender,
  generation = EXCLUDED.generation,
  father_id = EXCLUDED.father_id,
  mother_ref = EXCLUDED.mother_ref,
  spouses = EXCLUDED.spouses,
  children = EXCLUDED.children;

-- ══════════════════════════════════════════════════════════
-- GENERATION 4 (79 membres)
-- ══════════════════════════════════════════════════════════

INSERT INTO members (id, name, alias, gender, generation, father_id, mother_ref, spouses, children) VALUES
  ('hamadahamane_al', 'Hamadahamane Alhady', 'Larbou', 'M', 4, NULL, 'garba_g', '{}', '{}'),
  ('albakaya_al', 'Albakaya Alhady', NULL, 'M', 4, NULL, 'garba_g', '{}', '{}'),
  ('yahiya_al', 'Yahiya Alhady', NULL, 'M', 4, NULL, 'garba_g', '{}', '{}'),
  ('ndolly_al', 'N''dolly Alhady', NULL, 'M', 4, NULL, 'garba_g', '{}', '{}'),
  ('hajarata_al', 'Hajarata Alhady', 'Haji', 'F', 4, NULL, 'garba_g', '{}', '{}'),
  ('mahamadou_k', 'Mahamadou Klimazou', NULL, 'M', 4, 'klimazou', NULL, '{}', '{}'),
  ('mohomone', 'Mohomone Mahamane', 'Galla', 'M', 4, 'mahamane', 'Aïcha Houneye', '{"(épouse inconnue)"}', '{"ibrahim_m","seydou_mo","ousmane_m","adama_m","hirinissa"}'),
  ('taya', 'Taya Mahamane', NULL, 'F', 4, 'mahamane', 'Aïcha Houneye', '{"Hamadahamane"}', '{"halimatou_h","assaliha_h","arboncana","hadaye"}'),
  ('ahmadou', 'Ahmadou Mahamane', 'Agawa', 'M', 4, 'mahamane', 'Adijatou Hamma', '{}', '{"hallachi","houreitou","aminata_ag"}'),
  ('yata', 'Yata Mahamane', NULL, 'F', 4, 'mahamane', 'Adijatou Hamma', '{"Assabi"}', '{"momo","adama_a","hounaijata","waykouti","daoulata","mouna_a","zeinaba"}'),
  ('issouf', 'Issouf Mahamane', 'Tabbo', 'M', 4, 'mahamane', 'Adijatou Hamma', '{"Haoua Assaliha","Nafissatou Achekou","Saffia Mahadi"}', '{"moulaye","adijatou_t","annoussourou","alassane_t","arhamatou_t","assaliha_t","yahiya_t"}'),
  ('halilou', 'Ibrahim Mahamane', 'Halilou', 'M', 4, 'mahamane', 'Aïcha Hamma', '{"Yolli Hamadalamine"}', '{"hamma","idrissa_h","mariam_h","aichata_h"}'),
  ('alhalil', 'Alhalil Mahamane', NULL, 'M', 4, 'mahamane', 'Aïcha Hamma', '{}', '{}'),
  ('aliou_m', 'Aliou Mahamane', NULL, 'M', 4, 'mahamane', 'Aïcha Hamma', '{}', '{}'),
  ('houzaye', 'Houzaye Mahamane', NULL, 'M', 4, 'mahamane', 'Aïcha Hamma', '{}', '{"moussa_hz","daouda_hz","aliou_hz","aramtou_hz","fatoumatou_hz","mariam_hz"}'),
  ('alassane_s', 'Alassane Mahamane', 'Sosso', 'M', 4, 'mahamane', 'Aïcha Hamma', '{"Aminta N''Goiba Kabongou"}', '{"alhabibou","alkassoume","ibrahim_a","abdourhamane_a","moussa_a","mariama_a","safietou_a","hamsatou","arhamatou_a","hawa_a","bintou","aichata_a"}'),
  ('agaicha_m', 'Agaichatou Mahamane', NULL, 'F', 4, 'mahamane', 'Aïcha Hamma', '{"Tallo"}', '{"hamani_t","salama_t"}'),
  ('abdou_d', 'Abdou Mahamane', 'Doudou', 'M', 4, 'mahamane', 'Aïcha Hamma', '{"Bacha Tabbo","Arhama Ibrahim"}', '{"ichata_d","saley_d","hanchata","zaouzata","sarata","akilou","moukaila","daouda","sadou_d","idrissa_d"}'),
  ('aliou_b', 'Aliou Babachigaw', NULL, 'M', 4, 'babachigaw', 'Halimatou Mohomodou', '{"Halimatou Hamadahamane","Salama Amiro"}', '{"mohomodou_ab","idrissa_ab","issoufi_ab","abdoulaye_ab"}'),
  ('aboubacar', 'Aboubacar Babachigaw', 'Diamma', 'M', 4, 'babachigaw', 'Halimatou Mohomodou', '{}', '{"abdourhamane_di","aminata_di"}'),
  ('ousmane_a', 'Ousmane Babachigaw', 'Achidago', 'M', 4, 'babachigaw', 'Halimatou Mohomodou', '{}', '{"harouna","hamadahamane_ou","alassane_ou","nouhou_ou"}'),
  ('alhousseini', 'Alhousseini Babachigaw', 'Aggada', 'M', 4, 'babachigaw', 'Halimatou Mohomodou', '{"Mata Alphary (Tamimoune)"}', '{"hakimoune","hamida","houna","zabbo_ag"}'),
  ('abdoulaye_s', 'Abdoulaye Babachigaw', 'Sagara', 'M', 4, 'babachigaw', 'Halimatou Mohomodou', '{}', '{}'),
  ('nouhoum', 'Nouhou Babachigaw', NULL, 'M', 4, 'babachigaw', 'Halimatou Mohomodou', '{}', '{"issiaka_no","abdourhamane_no"}'),
  ('mata_b', 'Mata Babachigaw', NULL, 'F', 4, 'babachigaw', 'Halimatou Mohomodou', '{}', '{}'),
  ('mata_m', 'Mata Moussa', NULL, 'F', 4, 'moussa', 'Habïlatou Mama', '{}', '{}'),
  ('haylloli', 'Haylloli Moussa', NULL, 'F', 4, 'moussa', 'Habïlatou Mama', '{}', '{}'),
  ('wanaissou_m', 'Wanaissou Moussa', NULL, 'M', 4, 'moussa', 'Habïlatou Mama', '{}', '{}'),
  ('jato', 'Jato Moussa', NULL, 'F', 4, 'moussa', 'Habïlatou Mama', '{}', '{}'),
  ('alassane_m', 'Alassane Moussa', NULL, 'M', 4, 'moussa', 'Habïlatou Mama', '{}', '{}'),
  ('assoumane_m', 'Assoumane Moussa', NULL, 'M', 4, 'moussa', 'Habïlatou Mama', '{}', '{}'),
  ('abdou_m', 'Abdou Moussa', 'Boudou', 'M', 4, 'moussa', 'Habïlatou Mama', '{}', '{}'),
  ('sala', 'Sala Moussa', NULL, 'M', 4, 'moussa', 'Habïlatou Mama', '{}', '{}'),
  ('houssouba', 'Houssouba Omorou', NULL, 'M', 4, 'omorou', 'Cheffou Aliou', '{}', '{}'),
  ('kabongou', 'Kabongou Omorou', NULL, 'M', 4, 'omorou', 'Cheffou Aliou', '{}', '{"wayo","aminta_k","makiou","yacouba","ngolo","issiaka"}'),
  ('mahamadou_o', 'Mahamadou Omorou', NULL, 'M', 4, 'omorou', 'Cheffou Aliou', '{"Izéboncana Bangando"}', '{"zeinabou","koddo_m","bouba_m"}'),
  ('sourgou', 'Ibrahim Omorou', 'Sourgou', 'M', 4, 'omorou', 'Cheffou Aliou', '{}', '{"adija_s","mariama_s","fatoumata_s","ammou","bouba_s","koddo_s"}'),
  ('tabbo_o', 'Tabbo Omorou', 'Abdoulaye', 'M', 4, 'omorou', 'Cheffou Aliou', '{"Saffia Mahadi"}', '{"almahamoudou","minkailou","bacha","moumoumini","gallou","soumma","sadou_t"}'),
  ('zabbo', 'Zabbo Omorou', NULL, 'F', 4, 'omorou', 'Cheffou Aliou', '{}', '{}'),
  ('ichata_o', 'Ichata Omorou', NULL, 'F', 4, 'omorou', 'Cheffou Aliou', '{}', '{"alhoussouna","hachimine","hallachi","houreita_a","mariama_dj","haoua_dj","aminta_dj","haja"}'),
  ('chiddaye', 'Chiddaye Alphary', NULL, 'M', 4, 'alphary_g', 'tamimoune', '{"Bintou Mayloule"}', '{"djiougou","arhamatou_ch"}'),
  ('mata_a', 'Mata Alphary', NULL, 'F', 4, 'alphary_g', 'tamimoune', '{"Alhousseini Babachigaw (Aggada)"}', '{"hakimoune","hamida","houna","zabbo_ag"}'),
  ('ichata_a', 'Ichata Alphary', 'Aissata', 'F', 4, 'alphary_g', 'tamimoune', '{}', '{}'),
  ('boudjal', 'Boudjal Alphary', 'Boudia', 'M', 4, 'alphary_g', 'tamimoune', '{}', '{}'),
  ('saleymatou', 'Saleymatou Alphary', NULL, 'F', 4, 'alphary_g', 'tamimoune', '{"Ario Salo de Zindiga"}', '{"salo"}'),
  ('dayo', 'Dayo Mahadi', NULL, 'F', 4, 'mahadi', 'Aldjannatou Ahmadou', '{}', '{}'),
  ('saffia', 'Saffia Mahadi', NULL, 'F', 4, 'mahadi', 'Aldjannatou Ahmadou', '{}', '{}'),
  ('sawde', 'Sawde Mahadi', NULL, 'F', 4, 'mahadi', 'Aldjannatou Ahmadou', '{}', '{}'),
  ('zarha', 'Zarha Mahadi', NULL, 'F', 4, 'mahadi', 'Aldjannatou Ahmadou', '{}', '{}'),
  ('aminta_m', 'Aminta Mahadi', NULL, 'F', 4, 'mahadi', 'Aldjannatou Ahmadou', '{}', '{}'),
  ('chaffa', 'Chaffa Mahadi', NULL, 'M', 4, 'mahadi', 'Aldjannatou Ahmadou', '{}', '{}'),
  ('seydou_m', 'Seydou Mahadi', NULL, 'M', 4, 'mahadi', 'Aldjannatou Ahmadou', '{}', '{"babeye","abaneye","adija_se","chidi","arhamatou_se","mariama_se","ali_se","bibata","abdoulaye_se","saleye"}'),
  ('aicha_f', 'Aicha Fedja', NULL, 'F', 4, 'fedja_zongo', 'kobbo', '{}', '{"safietou_h","farimata_h","mohomodou_h","haoua_h","adama_h"}'),
  ('arhamatou_f', 'Arhamatou Fedja', NULL, 'F', 4, 'fedja_zongo', 'kobbo', '{}', '{"fatou_m","maimouna_m","yahiya_m","mommo_m","wanaissou_b"}'),
  ('issa_m', 'Issa Mohomodou', NULL, 'M', 4, 'mouhammadou_gagay', 'kobbo', '{}', '{"mohomone_i","haoua_i"}'),
  ('taya_m', 'Taya Mohomodou', NULL, 'M', 4, 'mouhammadou_gagay', 'kobbo', '{}', '{"babba","noussoura","kabongou_a"}'),
  ('izeboncana', 'Izeboncana Tayda', NULL, 'F', 4, 'taida_hounei', 'kobbo', '{}', '{"timintika","sawata","zarha_b"}'),
  ('jaouja', 'Jaouja Tayda', NULL, 'F', 4, 'taida_hounei', 'kobbo', '{}', '{"chidiya","ichata_ha"}'),
  ('dally', 'Dally Tayda', NULL, 'F', 4, 'taida_hounei', 'kobbo', '{}', '{"arhamatou_d","hancha","idrissa_da","abdoulaye_d","mouna_d","bouba_d","souma","koddo_d"}'),
  ('omorou_ab', 'Omorou Aboubaye', NULL, 'M', 4, NULL, 'halimatou_alk', '{}', '{}'),
  ('hamaya', 'Hamaya Aboubaye', NULL, 'M', 4, NULL, 'halimatou_alk', '{}', '{}'),
  ('farimata_ab', 'Farimata Aboubaye', 'Falladia', 'F', 4, NULL, 'halimatou_alk', '{}', '{}'),
  ('halimatou_moh', 'Halimatou Mohomodou', NULL, 'F', 4, 'mohomodou_alk', 'Fatoumata Molla Kader', '{}', '{}'),
  ('alkalifa', 'Alkalifa Mohomodou', NULL, 'M', 4, 'mohomodou_alk', 'Fatoumata Molla Kader', '{}', '{}'),
  ('ichata_moh', 'Ichata Mohomodou', NULL, 'F', 4, 'mohomodou_alk', 'Fatoumata Molla Kader', '{}', '{}'),
  ('tabati', 'Tabati Mohomodou', NULL, 'F', 4, 'mohomodou_alk', 'Fatoumata Molla Kader', '{}', '{}'),
  ('djinna', 'Djinna Mohomodou', NULL, 'F', 4, 'mohomodou_alk', 'Fatoumata Molla Kader', '{}', '{}'),
  ('abacar_moh', 'Abacar Mohomodou', NULL, 'M', 4, 'mohomodou_alk', 'Fatoumata Molla Kader', '{}', '{}'),
  ('kabongou_moy', 'Kabongou Moyadji', NULL, 'M', 4, NULL, 'fadimata_alk', '{}', '{}'),
  ('boubaye_moy', 'Boubaye Moyadji', NULL, 'M', 4, NULL, 'fadimata_alk', '{}', '{}'),
  ('alhassane_moy', 'Alhassane Moyadji', NULL, 'M', 4, NULL, 'fadimata_alk', '{}', '{}'),
  ('agacha_moy', 'Agacha Moyadji', NULL, 'F', 4, NULL, 'fadimata_alk', '{}', '{}'),
  ('oura', 'Oura Bana', NULL, 'F', 4, NULL, 'bana', '{}', '{}'),
  ('abdoulaye_ch', 'Abdoulaye Chirime', 'Mouta', 'M', 4, NULL, 'hailalle', '{}', '{}'),
  ('abacar_ch', 'Abacar Chirime', NULL, 'M', 4, NULL, 'hailalle', '{}', '{}'),
  ('mouazou', 'Mouazou Chirime', NULL, 'M', 4, NULL, 'hailalle', '{}', '{}'),
  ('fatto', 'Fatto Chirime', NULL, 'F', 4, NULL, 'hailalle', '{}', '{}'),
  ('ibrayhawi', 'Ibrayhawi Chirime', NULL, 'M', 4, NULL, 'hailalle', '{}', '{}'),
  ('abacar_sidi', 'Abacar Sidi', NULL, 'M', 4, NULL, 'zahara_alk', '{}', '{}')
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  alias = EXCLUDED.alias,
  gender = EXCLUDED.gender,
  generation = EXCLUDED.generation,
  father_id = EXCLUDED.father_id,
  mother_ref = EXCLUDED.mother_ref,
  spouses = EXCLUDED.spouses,
  children = EXCLUDED.children;

-- ══════════════════════════════════════════════════════════
-- GENERATION 5 (146 membres)
-- ══════════════════════════════════════════════════════════

INSERT INTO members (id, name, alias, gender, generation, father_id, mother_ref, spouses, children) VALUES
  ('moulaye', 'Moulaye Tabbo', NULL, 'M', 5, 'issouf', 'Haoua Assaliha', '{}', '{}'),
  ('adijatou_t', 'Adijatou Tabbo', NULL, 'F', 5, 'issouf', 'Haoua Assaliha', '{}', '{}'),
  ('annoussourou', 'Annoussourou Tabbo', NULL, 'M', 5, 'issouf', 'Nafissatou Achekou', '{}', '{}'),
  ('alassane_t', 'Alassane Tabbo', 'Boncana', 'M', 5, 'issouf', 'Nafissatou Achekou', '{}', '{}'),
  ('arhamatou_t', 'Arhamatou Tabbo', NULL, 'F', 5, 'issouf', 'Nafissatou Achekou', '{}', '{}'),
  ('assaliha_t', 'Assaliha Tabbo', NULL, 'F', 5, 'issouf', 'Nafissatou Achekou', '{}', '{}'),
  ('yahiya_t', 'Yahiya Tabbo', NULL, 'M', 5, 'issouf', 'Saffia Mahadi', '{}', '{}'),
  ('momo', 'Momo Assabi', NULL, 'M', 5, NULL, 'yata', '{}', '{}'),
  ('adama_a', 'Adama Assabi', NULL, 'M', 5, NULL, 'yata', '{}', '{}'),
  ('hounaijata', 'Hounaijata Assabi', NULL, 'F', 5, NULL, 'yata', '{}', '{}'),
  ('waykouti', 'Waykouti Assabi', NULL, 'F', 5, NULL, 'yata', '{}', '{}'),
  ('daoulata', 'Daoulata Assabi', NULL, 'F', 5, NULL, 'yata', '{}', '{}'),
  ('mouna_a', 'Mouna Assabi', NULL, 'F', 5, NULL, 'yata', '{}', '{}'),
  ('zeinaba', 'Zeinaba Assabi', NULL, 'F', 5, NULL, 'yata', '{}', '{}'),
  ('alhabibou', 'Abdoulaye Alassane', 'Alhabibou', 'M', 5, 'alassane_s', 'Aminta N''Goiba', '{}', '{}'),
  ('alkassoume', 'Alkassoume Alassane', NULL, 'M', 5, 'alassane_s', 'Aminta N''Goiba', '{}', '{}'),
  ('ibrahim_a', 'Ibrahim Alassane', 'Bruno', 'M', 5, 'alassane_s', 'Aminta N''Goiba', '{"Leïla Abdourhamane Maiga"}', '{"ahmed_salia"}'),
  ('abdourhamane_a', 'Abdourhamane Alassane', 'Doumma', 'M', 5, 'alassane_s', 'Aminta N''Goiba', '{}', '{}'),
  ('moussa_a', 'Moussa Alassane', 'Assani', 'M', 5, 'alassane_s', 'Aminta N''Goiba', '{"Lalla Az-Zahra Almoudou Touré","Mariame Boubacar Alassane Wanaysou"}', '{"alassane_ma","abdoulaye_ma","ibrahim_ma","abdourahman_ma","hadijatou_ma","zoumouroudatou","arrahmatoulahi","azzahratou","mariame_ma","aminata_ma","alkassoum_ma","mohammed_ma","hamidou_ma"}'),
  ('mariama_a', 'Mariama Alassane', NULL, 'F', 5, 'alassane_s', 'Aminta N''Goiba', '{}', '{}'),
  ('safietou_a', 'Safietou Alassane', NULL, 'F', 5, 'alassane_s', 'Aminta N''Goiba', '{}', '{}'),
  ('hamsatou', 'Hamsatou Alassane', NULL, 'F', 5, 'alassane_s', 'Aminta N''Goiba', '{}', '{}'),
  ('arhamatou_a', 'Arhamatou Alassane', NULL, 'F', 5, 'alassane_s', 'Aminta N''Goiba', '{}', '{}'),
  ('hawa_a', 'Hawa Alassane', NULL, 'F', 5, 'alassane_s', 'Aminta N''Goiba', '{}', '{}'),
  ('bintou', 'Bintou Alassane', NULL, 'F', 5, 'alassane_s', 'Aminta N''Goiba', '{}', '{}'),
  ('aichata_a', 'Aichata Alassane', NULL, 'F', 5, 'alassane_s', 'Aminta N''Goiba', '{}', '{}'),
  ('ibrahim_m', 'Ibrahim Mohomone', NULL, 'M', 5, 'mohomone', NULL, '{}', '{}'),
  ('seydou_mo', 'Seydou Mohomone', NULL, 'M', 5, 'mohomone', NULL, '{}', '{}'),
  ('ousmane_m', 'Ousmane Mohomone', NULL, 'M', 5, 'mohomone', NULL, '{}', '{}'),
  ('adama_m', 'Adama Mohomone', NULL, 'M', 5, 'mohomone', NULL, '{}', '{}'),
  ('hirinissa', 'Hirinissa Mohomone', 'Aichata', 'F', 5, 'mohomone', NULL, '{}', '{}'),
  ('hamma', 'Hamma Halilou', 'Ario', 'M', 5, 'halilou', 'Yolli Hamadalamine', '{}', '{}'),
  ('idrissa_h', 'Idrissa Halilou', NULL, 'M', 5, 'halilou', 'Yolli Hamadalamine', '{}', '{}'),
  ('mariam_h', 'Mariam Halilou', NULL, 'F', 5, 'halilou', 'Yolli Hamadalamine', '{}', '{}'),
  ('aichata_h', 'Aichata Halilou', NULL, 'F', 5, 'halilou', 'Yolli Hamadalamine', '{}', '{}'),
  ('halimatou_h', 'Halimatou Hamadahamane', 'Larbou', 'F', 5, NULL, 'taya', '{"Aliou"}', '{"aichata_al","fadimata_al","haoua_al","fatoumata_al","hajarta_al","mohomodou_al","idrissa_al"}'),
  ('assaliha_h', 'Assaliha Hamadahamane', 'Larbou', 'M', 5, NULL, 'taya', '{}', '{"waiyou","lalla_as","adizatou_as","fato_as","ibrahim_as","alassane_as","alousseiny_as"}'),
  ('arboncana', 'Arboncana Hamadahamane', NULL, 'M', 5, NULL, 'taya', '{}', '{"salamata_ar","fato_ar"}'),
  ('hadaye', 'Hadaye Hamadahamane', NULL, 'F', 5, 'taya', NULL, '{}', '{}'),
  ('ichata_d', 'Ichata Doudou', NULL, 'F', 5, 'abdou_d', 'Bacha Tabbo', '{}', '{}'),
  ('saley_d', 'Saley Doudou', NULL, 'M', 5, 'abdou_d', 'Bacha Tabbo', '{}', '{}'),
  ('hanchata', 'Hanchata Doudou', NULL, 'F', 5, 'abdou_d', 'Bacha Tabbo', '{}', '{}'),
  ('zaouzata', 'Zaouzata Doudou', NULL, 'F', 5, 'abdou_d', 'Bacha Tabbo', '{}', '{}'),
  ('sarata', 'Sarata Doudou', NULL, 'F', 5, 'abdou_d', 'Bacha Tabbo', '{}', '{}'),
  ('akilou', 'Akilou Doudou', NULL, 'M', 5, 'abdou_d', 'Bacha Tabbo', '{}', '{}'),
  ('moukaila', 'Moukaila Doudou', NULL, 'M', 5, 'abdou_d', 'Bacha Tabbo', '{}', '{}'),
  ('daouda', 'Daouda Doudou', NULL, 'M', 5, 'abdou_d', 'Bacha Tabbo', '{}', '{}'),
  ('sadou_d', 'Sadou Doudou', NULL, 'M', 5, 'abdou_d', 'Bacha Tabbo', '{}', '{}'),
  ('idrissa_d', 'Idrissa Doudou', NULL, 'M', 5, 'abdou_d', 'Bacha Tabbo', '{}', '{}'),
  ('wayo', 'Wayo Kabongou', 'N''goyba', 'M', 5, 'kabongou', NULL, '{}', '{}'),
  ('aminta_k', 'Aminta Kabongou', 'N''goyba', 'F', 5, 'kabongou', NULL, '{}', '{}'),
  ('makiou', 'Makiou Kabongou', 'N''goyba', 'M', 5, 'kabongou', NULL, '{}', '{}'),
  ('yacouba', 'Yacouba Kabongou', 'N''goyba', 'M', 5, 'kabongou', NULL, '{}', '{}'),
  ('ngolo', 'N''Golo Kabongou', 'N''goyba', 'M', 5, 'kabongou', NULL, '{}', '{}'),
  ('issiaka', 'Issiaka Kabongou', 'N''goyba', 'M', 5, 'kabongou', NULL, '{}', '{}'),
  ('zeinabou', 'Zeinabou Mahamadou', NULL, 'F', 5, 'mahamadou_o', 'Izéboncana Bangando', '{}', '{}'),
  ('koddo_m', 'Koddo Mahamadou', NULL, 'F', 5, 'mahamadou_o', 'Izéboncana Bangando', '{}', '{}'),
  ('bouba_m', 'Bouba Mahamadou', NULL, 'M', 5, 'mahamadou_o', 'Izéboncana Bangando', '{}', '{}'),
  ('adija_s', 'Adija Sourgou', NULL, 'F', 5, 'sourgou', 'Ibania Seydou', '{}', '{}'),
  ('mariama_s', 'Mariama Sourgou', NULL, 'F', 5, 'sourgou', 'Ibania Seydou', '{}', '{}'),
  ('fatoumata_s', 'Fatoumata Sourgou', NULL, 'F', 5, 'sourgou', 'Ibania Seydou', '{}', '{}'),
  ('ammou', 'Ammou Sourgou', NULL, 'F', 5, 'sourgou', '(à définir)', '{}', '{}'),
  ('bouba_s', 'Bouba Sourgou', NULL, 'M', 5, 'sourgou', '(à définir)', '{}', '{}'),
  ('koddo_s', 'Aichata Sourgou', 'Koddo', 'F', 5, 'sourgou', '(à définir)', '{}', '{}'),
  ('almahamoudou', 'Almahamoudou Tabagore', 'Illile', 'M', 5, 'tabbo_o', 'Saffia Mahadi', '{}', '{}'),
  ('minkailou', 'Minkailou Tabagore', 'Kila', 'M', 5, 'tabbo_o', 'Saffia Mahadi', '{}', '{}'),
  ('bacha', 'Bacha Tabagore', NULL, 'M', 5, 'tabbo_o', 'Saffia Mahadi', '{}', '{}'),
  ('moumoumini', 'Moumoumini Tabagore', 'Belleythiero', 'M', 5, 'tabbo_o', 'Saffia Mahadi', '{}', '{}'),
  ('gallou', 'Gallou Tabagore', NULL, 'M', 5, 'tabbo_o', 'Saffia Mahadi', '{}', '{}'),
  ('soumma', 'Soumma Tabagore', NULL, 'M', 5, 'tabbo_o', 'Saffia Mahadi', '{}', '{}'),
  ('sadou_t', 'Sadou Tabagore', NULL, 'M', 5, 'tabbo_o', 'Saffia Mahadi', '{}', '{}'),
  ('alhoussouna', 'Alhoussouna Bodowal', NULL, 'M', 5, NULL, 'ichata_o', '{}', '{}'),
  ('hachimine', 'Hachimine Bodowal', NULL, 'M', 5, NULL, 'ichata_o', '{}', '{}'),
  ('hallachi', 'Alassane Ahmadou', 'Hallachi', 'M', 5, 'ahmadou', NULL, '{}', '{"mohomodou_ha","abdoulkadri","attahir","alassane_ha","houzeye_ha","chitta","abdoulkarim","mohomodou_ha2"}'),
  ('houreita_a', 'Houreita Agawa', NULL, 'F', 5, NULL, 'ichata_o', '{}', '{}'),
  ('mariama_dj', 'Mariama Djama', NULL, 'F', 5, NULL, 'ichata_o', '{}', '{}'),
  ('haoua_dj', 'Haoua Djama', NULL, 'F', 5, NULL, 'ichata_o', '{}', '{}'),
  ('aminta_dj', 'Aminta Djama', NULL, 'F', 5, NULL, 'ichata_o', '{}', '{}'),
  ('haja', 'Haja Galleye', NULL, 'F', 5, NULL, 'ichata_o', '{}', '{}'),
  ('babeye', 'Babeye Seydou', NULL, 'M', 5, 'seydou_m', NULL, '{}', '{}'),
  ('abaneye', 'Abaneye Seydou', NULL, 'M', 5, 'seydou_m', NULL, '{}', '{}'),
  ('adija_se', 'Adija Seydou', NULL, 'F', 5, 'seydou_m', NULL, '{}', '{}'),
  ('chidi', 'Chidi Seydou', NULL, 'M', 5, 'seydou_m', NULL, '{}', '{}'),
  ('arhamatou_se', 'Arhamatou Seydou', NULL, 'F', 5, 'seydou_m', NULL, '{}', '{}'),
  ('mariama_se', 'Mariama Seydou', NULL, 'F', 5, 'seydou_m', NULL, '{}', '{}'),
  ('ali_se', 'Ali Seydou', NULL, 'M', 5, 'seydou_m', NULL, '{}', '{}'),
  ('bibata', 'Bibata Seydou', NULL, 'F', 5, 'seydou_m', NULL, '{}', '{}'),
  ('abdoulaye_se', 'Abdoulaye Seydou', NULL, 'M', 5, 'seydou_m', NULL, '{}', '{}'),
  ('saleye', 'Saleye Seydou', NULL, 'M', 5, 'seydou_m', NULL, '{}', '{}'),
  ('djiougou', 'Djiougou Chideye', NULL, 'M', 5, 'chiddaye', 'Bintou Mayloule', '{}', '{}'),
  ('arhamatou_ch', 'Arhamatou Chideye', NULL, 'F', 5, 'chiddaye', NULL, '{}', '{}'),
  ('hakimoune', 'Hakimoune Aggada', NULL, 'M', 5, 'alhousseini', 'mata_a', '{}', '{}'),
  ('hamida', 'Hamida Aggada', NULL, 'F', 5, 'alhousseini', 'mata_a', '{}', '{}'),
  ('houna', 'Houna Aggada', NULL, 'F', 5, 'alhousseini', 'mata_a', '{}', '{}'),
  ('zabbo_ag', 'Zabbo Aggada', NULL, 'F', 5, 'alhousseini', 'mata_a', '{}', '{}'),
  ('salo', 'Salo Alkassahi', NULL, 'M', 5, NULL, 'saleymatou', '{}', '{}'),
  ('safietou_h', 'Safietou Hanakoukou', NULL, 'F', 5, NULL, 'aicha_f', '{}', '{}'),
  ('farimata_h', 'Farimata Hanakoukou', NULL, 'F', 5, NULL, 'aicha_f', '{}', '{}'),
  ('mohomodou_h', 'Mohomodou Hanakoukou', 'Mawal', 'M', 5, NULL, 'aicha_f', '{}', '{}'),
  ('haoua_h', 'Haoua Hanakoukou', NULL, 'F', 5, NULL, 'aicha_f', '{}', '{}'),
  ('adama_h', 'Adama Hanakoukou', NULL, 'M', 5, NULL, 'aicha_f', '{}', '{}'),
  ('fatou_m', 'Fatou Moussa', NULL, 'F', 5, NULL, 'arhamatou_f', '{}', '{}'),
  ('maimouna_m', 'Maimouna Moussa', NULL, 'F', 5, NULL, 'arhamatou_f', '{}', '{}'),
  ('yahiya_m', 'Yahiya Moussa', NULL, 'M', 5, NULL, 'arhamatou_f', '{}', '{}'),
  ('mommo_m', 'Mommo Moussa', NULL, 'M', 5, NULL, 'arhamatou_f', '{}', '{}'),
  ('wanaissou_b', 'Wanaissou Moussa Bahadou', NULL, 'M', 5, NULL, 'arhamatou_f', '{}', '{}'),
  ('babba', 'Babba Amiro', NULL, 'M', 5, 'taya_m', NULL, '{}', '{}'),
  ('noussoura', 'Noussoura Amiro', NULL, 'F', 5, 'taya_m', NULL, '{}', '{}'),
  ('kabongou_a', 'Kabongou Amiro', NULL, 'M', 5, 'taya_m', NULL, '{}', '{}'),
  ('mohomone_i', 'Mohomone Issa', NULL, 'M', 5, 'issa_m', NULL, '{}', '{}'),
  ('haoua_i', 'Haoua Issa', 'N''gary', 'F', 5, 'issa_m', NULL, '{}', '{}'),
  ('timintika', 'Timintika Bodowal', NULL, 'F', 5, NULL, 'izeboncana', '{}', '{}'),
  ('sawata', 'Sawata Bodowal', NULL, 'F', 5, NULL, 'izeboncana', '{}', '{}'),
  ('zarha_b', 'Zarha Bodowal', NULL, 'F', 5, NULL, 'izeboncana', '{}', '{}'),
  ('chidiya', 'Chidiya Halimine', NULL, 'F', 5, NULL, 'jaouja', '{}', '{}'),
  ('ichata_ha', 'Ichata Halimine', NULL, 'F', 5, NULL, 'jaouja', '{}', '{}'),
  ('arhamatou_d', 'Arhamatou Dally', NULL, 'F', 5, NULL, 'dally', '{}', '{}'),
  ('hancha', 'Hancha Dally', NULL, 'F', 5, NULL, 'dally', '{}', '{}'),
  ('idrissa_da', 'Idrissa Dally', NULL, 'M', 5, NULL, 'dally', '{}', '{}'),
  ('abdoulaye_d', 'Abdoulaye Dally', NULL, 'M', 5, NULL, 'dally', '{}', '{}'),
  ('mouna_d', 'Mouna Dally', NULL, 'F', 5, NULL, 'dally', '{}', '{}'),
  ('bouba_d', 'Bouba Dally', NULL, 'M', 5, NULL, 'dally', '{}', '{}'),
  ('souma', 'Souma Dally', NULL, 'F', 5, NULL, 'dally', '{}', '{}'),
  ('koddo_d', 'Koddo Dally', NULL, 'F', 5, NULL, 'dally', '{}', '{}'),
  ('houreitou', 'Houreitou Ahmadou', NULL, 'F', 5, 'ahmadou', NULL, '{}', '{}'),
  ('aminata_ag', 'Aminata Ahmadou', NULL, 'F', 5, 'ahmadou', NULL, '{}', '{}'),
  ('moussa_hz', 'Moussa Houzaye', NULL, 'M', 5, 'houzaye', NULL, '{}', '{}'),
  ('daouda_hz', 'Daouda Houzaye', NULL, 'M', 5, 'houzaye', NULL, '{}', '{"mahamane_dh","moussa_dh","moumini_dh"}'),
  ('aliou_hz', 'Aliou Houzaye', NULL, 'M', 5, 'houzaye', NULL, '{}', '{"houzeye_ah","daouda_ah","moumini_ah"}'),
  ('aramtou_hz', 'Aramtou Houzaye', NULL, 'F', 5, 'houzaye', NULL, '{}', '{}'),
  ('fatoumatou_hz', 'Fatoumatou Houzaye', NULL, 'F', 5, 'houzaye', NULL, '{}', '{}'),
  ('mariam_hz', 'Mariam Houzaye', NULL, 'F', 5, 'houzaye', NULL, '{}', '{}'),
  ('hamani_t', 'Hamani Tallo', NULL, 'M', 5, 'Tallo', 'agaicha_m', '{}', '{"bossou"}'),
  ('salama_t', 'Salama Tallo', NULL, 'F', 5, 'Tallo', 'agaicha_m', '{}', '{}'),
  ('mohomodou_ab', 'Mohomodou Aliou', NULL, 'M', 5, 'aliou_b', NULL, '{}', '{"abdoulwahab","hamidou_mab","faissal","imrana_mab"}'),
  ('idrissa_ab', 'Idrissa Aliou', NULL, 'M', 5, 'aliou_b', NULL, '{}', '{"abdoulaye_iab","aboubacar_iab","yehiya_iab","issiaka_iab","issoufi_iab"}'),
  ('issoufi_ab', 'Issoufi Aliou', NULL, 'M', 5, 'aliou_b', NULL, '{}', '{"yehiya_is","aliou_is"}'),
  ('abdoulaye_ab', 'Abdoulaye Aliou', NULL, 'M', 5, 'aliou_b', NULL, '{}', '{"idrissa_aab"}'),
  ('abdourhamane_di', 'Abdourhamane Aboubacar', 'Diamma', 'M', 5, 'aboubacar', NULL, '{}', '{}'),
  ('aminata_di', 'Aminata Aboubacar', 'Diamma', 'F', 5, 'aboubacar', NULL, '{}', '{}'),
  ('harouna', 'Harouna Ousmane', 'Achidago', 'M', 5, 'ousmane_a', NULL, '{}', '{"abdoulback","ibrahim_ha","sadou_ha","mahamoudou_ha","alkassoum_ha"}'),
  ('hamadahamane_ou', 'Hamadahamane Ousmane', 'Achidago', 'M', 5, 'ousmane_a', NULL, '{}', '{}'),
  ('alassane_ou', 'Alassane Ousmane', 'Achidago', 'M', 5, 'ousmane_a', NULL, '{}', '{}'),
  ('nouhou_ou', 'Nouhou Ousmane', 'Achidago', 'M', 5, 'ousmane_a', NULL, '{}', '{}'),
  ('issiaka_no', 'Issiaka Nouhou', NULL, 'M', 5, 'nouhoum', NULL, '{}', '{"idrissa_is","mafouzou"}'),
  ('abdourhamane_no', 'Abdourhamane Nouhou', NULL, 'M', 5, 'nouhoum', NULL, '{}', '{"halidou_ab"}')
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  alias = EXCLUDED.alias,
  gender = EXCLUDED.gender,
  generation = EXCLUDED.generation,
  father_id = EXCLUDED.father_id,
  mother_ref = EXCLUDED.mother_ref,
  spouses = EXCLUDED.spouses,
  children = EXCLUDED.children;

-- ══════════════════════════════════════════════════════════
-- GENERATION 6 (65 membres)
-- ══════════════════════════════════════════════════════════

INSERT INTO members (id, name, alias, gender, generation, father_id, mother_ref, spouses, children) VALUES
  ('alassane_ma', 'Alassane Moussa Alassane', 'décédé', 'M', 6, 'moussa_a', 'Lalla Az-Zahra Almoudou Touré', '{}', '{}'),
  ('abdoulaye_ma', 'Abdoulaye Alhabib Moussa Alassane', NULL, 'M', 6, 'moussa_a', 'Lalla Az-Zahra Almoudou Touré', '{}', '{}'),
  ('ibrahim_ma', 'Ibrahim Haliloulahi Moussa Alassane', NULL, 'M', 6, 'moussa_a', 'Lalla Az-Zahra Almoudou Touré', '{}', '{}'),
  ('abdourahman_ma', 'Abdourahman Moussa Alassane', NULL, 'M', 6, 'moussa_a', 'Lalla Az-Zahra Almoudou Touré', '{}', '{}'),
  ('hadijatou_ma', 'Hadijatou Moussa Alassane', NULL, 'F', 6, 'moussa_a', 'Lalla Az-Zahra Almoudou Touré', '{}', '{}'),
  ('zoumouroudatou', 'Zoumouroudatou Moussa Alassane', NULL, 'F', 6, 'moussa_a', 'Lalla Az-Zahra Almoudou Touré', '{}', '{}'),
  ('arrahmatoulahi', 'Ar-Rahmatoulahi Moussa Alassane', NULL, 'F', 6, 'moussa_a', 'Lalla Az-Zahra Almoudou Touré', '{}', '{}'),
  ('azzahratou', 'Az-Zahratou Moussa Alassane', NULL, 'F', 6, 'moussa_a', 'Lalla Az-Zahra Almoudou Touré', '{}', '{}'),
  ('mariame_ma', 'Mariame Moussa Alassane', 'décédée', 'F', 6, 'moussa_a', 'Mariame Boubacar Alassane Wanaysou', '{}', '{}'),
  ('aminata_ma', 'Aminata Moussa Alassane', NULL, 'F', 6, 'moussa_a', 'Mariame Boubacar Alassane Wanaysou', '{}', '{}'),
  ('alkassoum_ma', 'Alkassoum Moussa Alassane', NULL, 'M', 6, 'moussa_a', 'Mariame Boubacar Alassane Wanaysou', '{}', '{}'),
  ('mohammed_ma', 'Mohammed Taher Moussa Alassane', NULL, 'M', 6, 'moussa_a', 'Mariame Boubacar Alassane Wanaysou', '{}', '{}'),
  ('hamidou_ma', 'Hamidou Moussa Alassane', NULL, 'M', 6, 'moussa_a', 'Mariame Boubacar Alassane Wanaysou', '{}', '{}'),
  ('ahmed_salia', 'Ahmed Salia Toure', NULL, 'M', 6, 'ibrahim_a', 'Leïla Abdourhamane Maiga', '{"Kadidia Djibo Diango"}', '{"amadou_yusuf"}'),
  ('aichata_al', 'Aichata Aliou', 'Alido', 'F', 6, 'Aliou', 'halimatou_h', '{}', '{}'),
  ('fadimata_al', 'Fadimata Aliou', 'Fado', 'F', 6, 'Aliou', 'halimatou_h', '{}', '{}'),
  ('haoua_al', 'Haoua Aliou', NULL, 'F', 6, 'Aliou', 'halimatou_h', '{}', '{}'),
  ('fatoumata_al', 'Fatoumata Aliou', 'Balatou', 'F', 6, 'Aliou', 'halimatou_h', '{}', '{}'),
  ('hajarta_al', 'Hajarta Aliou', NULL, 'F', 6, 'Aliou', 'halimatou_h', '{}', '{}'),
  ('mohomodou_al', 'Mohomodou Aliou', NULL, 'M', 6, 'Aliou', 'halimatou_h', '{}', '{}'),
  ('idrissa_al', 'Idrissa Aliou', NULL, 'M', 6, 'Aliou', 'halimatou_h', '{}', '{}'),
  ('waiyou', 'Waiyou Assalia', NULL, 'M', 6, 'assaliha_h', NULL, '{}', '{}'),
  ('lalla_as', 'Lalla Assalia', NULL, 'F', 6, 'assaliha_h', NULL, '{}', '{}'),
  ('adizatou_as', 'Adizatou Assalia', NULL, 'F', 6, 'assaliha_h', NULL, '{}', '{}'),
  ('fato_as', 'Fato Assalia', NULL, 'F', 6, 'assaliha_h', NULL, '{}', '{}'),
  ('ibrahim_as', 'Ibrahim Assalia', 'Hagadoumba', 'M', 6, 'assaliha_h', NULL, '{}', '{}'),
  ('alassane_as', 'Alassane Assalia', NULL, 'M', 6, 'assaliha_h', NULL, '{}', '{}'),
  ('alousseiny_as', 'Alousseiny Assalia', NULL, 'M', 6, 'assaliha_h', NULL, '{}', '{}'),
  ('salamata_ar', 'Salamata Arboncana', 'Deybey', 'F', 6, 'arboncana', NULL, '{}', '{}'),
  ('fato_ar', 'Fato Arboncana', NULL, 'F', 6, 'arboncana', NULL, '{}', '{}'),
  ('mohomodou_ha', 'Mohomodou Alassane', 'Adama', 'M', 6, 'hallachi', NULL, '{}', '{"moussa_mh","doumma_mh"}'),
  ('abdoulkadri', 'Abdoulkadri Alassane', NULL, 'M', 6, 'hallachi', NULL, '{}', '{}'),
  ('attahir', 'Attahir Alassane', NULL, 'M', 6, 'hallachi', NULL, '{}', '{}'),
  ('alassane_ha', 'Alassane Alassane', 'Aoudou', 'M', 6, 'hallachi', NULL, '{}', '{"moulaye_ao","ibrahim_ao","mahamane_ao","oumar_ao"}'),
  ('houzeye_ha', 'Houzeye Alassane', NULL, 'M', 6, 'hallachi', NULL, '{}', '{}'),
  ('chitta', 'Chitta Alassane', NULL, 'M', 6, 'hallachi', NULL, '{}', '{"ibounia"}'),
  ('abdoulkarim', 'Abdoulkarim Alassane', NULL, 'M', 6, 'hallachi', NULL, '{}', '{}'),
  ('mohomodou_ha2', 'Mohomodou Alassane', NULL, 'M', 6, 'hallachi', NULL, '{}', '{}'),
  ('mahamane_dh', 'Mahamane Daouda', NULL, 'M', 6, 'daouda_hz', NULL, '{}', '{}'),
  ('moussa_dh', 'Moussa Daouda', NULL, 'M', 6, 'daouda_hz', NULL, '{}', '{}'),
  ('moumini_dh', 'Moumini Daouda', NULL, 'M', 6, 'daouda_hz', NULL, '{}', '{}'),
  ('houzeye_ah', 'Houzeye Aliou', NULL, 'M', 6, 'aliou_hz', NULL, '{}', '{}'),
  ('daouda_ah', 'Daouda Aliou', NULL, 'M', 6, 'aliou_hz', NULL, '{}', '{}'),
  ('moumini_ah', 'Moumini Aliou', NULL, 'M', 6, 'aliou_hz', NULL, '{}', '{}'),
  ('bossou', 'Bossou Hamani', NULL, 'M', 6, 'hamani_t', NULL, '{}', '{}'),
  ('abdoulwahab', 'Abdoulwahab Mohomodou', NULL, 'M', 6, 'mohomodou_ab', NULL, '{}', '{}'),
  ('hamidou_mab', 'Hamidou Mohomodou', NULL, 'M', 6, 'mohomodou_ab', NULL, '{}', '{}'),
  ('faissal', 'Faissal Mohomodou', NULL, 'M', 6, 'mohomodou_ab', NULL, '{}', '{}'),
  ('imrana_mab', 'Imrana Mohomodou', NULL, 'M', 6, 'mohomodou_ab', NULL, '{}', '{}'),
  ('abdoulaye_iab', 'Abdoulaye Idrissa', NULL, 'M', 6, 'idrissa_ab', NULL, '{}', '{}'),
  ('aboubacar_iab', 'Aboubacar Idrissa', NULL, 'M', 6, 'idrissa_ab', NULL, '{}', '{}'),
  ('yehiya_iab', 'Yehiya Idrissa', NULL, 'M', 6, 'idrissa_ab', NULL, '{}', '{}'),
  ('issiaka_iab', 'Issiaka Idrissa', NULL, 'M', 6, 'idrissa_ab', NULL, '{}', '{}'),
  ('issoufi_iab', 'Issoufi Idrissa', NULL, 'M', 6, 'idrissa_ab', NULL, '{}', '{}'),
  ('yehiya_is', 'Yehiya Issoufi', NULL, 'M', 6, 'issoufi_ab', NULL, '{}', '{}'),
  ('aliou_is', 'Aliou Issoufi', NULL, 'M', 6, 'issoufi_ab', NULL, '{}', '{}'),
  ('idrissa_aab', 'Idrissa Abdoulaye', NULL, 'M', 6, 'abdoulaye_ab', NULL, '{}', '{}'),
  ('abdoulback', 'Abdoulback Harouna', NULL, 'M', 6, 'harouna', NULL, '{}', '{}'),
  ('ibrahim_ha', 'Ibrahim Harouna', NULL, 'M', 6, 'harouna', NULL, '{}', '{"issoufi_ibh"}'),
  ('sadou_ha', 'Sadou Harouna', NULL, 'M', 6, 'harouna', NULL, '{}', '{}'),
  ('mahamoudou_ha', 'Mahamoudou Harouna', NULL, 'M', 6, 'harouna', NULL, '{}', '{}'),
  ('alkassoum_ha', 'Alkassoum Harouna', NULL, 'M', 6, 'harouna', NULL, '{}', '{}'),
  ('idrissa_is', 'Idrissa Issiaka', NULL, 'M', 6, 'issiaka_no', NULL, '{}', '{}'),
  ('mafouzou', 'Mafouzou Issiaka', NULL, 'M', 6, 'issiaka_no', NULL, '{}', '{}'),
  ('halidou_ab', 'Halidou Abdourhamane', NULL, 'M', 6, 'abdourhamane_no', NULL, '{}', '{}')
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  alias = EXCLUDED.alias,
  gender = EXCLUDED.gender,
  generation = EXCLUDED.generation,
  father_id = EXCLUDED.father_id,
  mother_ref = EXCLUDED.mother_ref,
  spouses = EXCLUDED.spouses,
  children = EXCLUDED.children;

-- ══════════════════════════════════════════════════════════
-- GENERATION 7 (9 membres)
-- ══════════════════════════════════════════════════════════

INSERT INTO members (id, name, alias, gender, generation, father_id, mother_ref, spouses, children) VALUES
  ('amadou_yusuf', 'Amadou-Yûsuf Toure', NULL, 'M', 7, 'ahmed_salia', 'Kadidia Djibo Diango', '{}', '{}'),
  ('moussa_mh', 'Moussa Mohomodou', NULL, 'M', 7, 'mohomodou_ha', NULL, '{}', '{}'),
  ('doumma_mh', 'Doumma Mohomodou', NULL, 'M', 7, 'mohomodou_ha', NULL, '{}', '{}'),
  ('moulaye_ao', 'Moulaye Alassane', NULL, 'M', 7, 'alassane_ha', NULL, '{}', '{}'),
  ('ibrahim_ao', 'Ibrahim Alassane', NULL, 'M', 7, 'alassane_ha', NULL, '{}', '{}'),
  ('mahamane_ao', 'Mahamane Alassane', NULL, 'M', 7, 'alassane_ha', NULL, '{}', '{}'),
  ('oumar_ao', 'Oumar Alassane', NULL, 'M', 7, 'alassane_ha', NULL, '{}', '{}'),
  ('ibounia', 'Ibounia Chitta', NULL, 'M', 7, 'chitta', NULL, '{}', '{}'),
  ('issoufi_ibh', 'Issoufi Ibrahim', NULL, 'M', 7, 'ibrahim_ha', NULL, '{}', '{}')
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  alias = EXCLUDED.alias,
  gender = EXCLUDED.gender,
  generation = EXCLUDED.generation,
  father_id = EXCLUDED.father_id,
  mother_ref = EXCLUDED.mother_ref,
  spouses = EXCLUDED.spouses,
  children = EXCLUDED.children;

-- ══════════════════════════════════════════════════════════
-- STATISTIQUES
-- Total: 342 membres
-- Hommes: 210 | Femmes: 132
-- Generations: G0 a G7 (8 generations)
-- ══════════════════════════════════════════════════════════
